version: "3"
services:
 reverseproxy:
   image: armadillo71/reverseproxy
   ports:
     - 8080:8080
   restart: always
   depends_on:
    - backend-user
    - backend-feed   
 backend-user:
  image: armadillo71/udagram-api-user
  volumes:
   - $HOME/.aws:/root/.aws
  environment:
   POSTGRES_USERNAME: $POSTGRES_USERNAME
   POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
   POSTGRES_DB: $POSTGRES_DB 
   POSTGRES_HOST: $POSTGRES_HOST 
   AWS_REGION: $AWS_REGION 
   AWS_PROFILE: $AWS_PROFILE 
   AWS_BUCKET: $AWS_BUCKET
   JWT_SECRET: $JWT_SECRET
   URL: "http://localhost:8100"
 backend-feed:
  image: armadillo71/udagram-api-feed
  volumes:
   - $HOME/.aws:/root/.aws
  environment:
   POSTGRES_USERNAME: $POSTGRESS_USERNAME
   POSTGRES_PASSWORD: $POSTGRESS_PASSWORD 
   POSTGRES_DB: $POSTGRESS_DB 
   POSTGRES_HOST: $POSTGRESS_HOST 
   AWS_REGION: $AWS_REGION 
   AWS_PROFILE: $AWS_PROFILE 
   AWS_BUCKET: $AWS_BUCKET
   JWT_SECRET: $JWT_SECRET
   URL: "http://localhost:8100"
 frontend:
  image: armadillo71/udagram-frontend
  ports:
   - "8100:80"